require('settings')
require('mappings')
-- Broken for some reason
-- require('colorschemes-config.nightfox')
require('colorschemes-config.onedarkpro')
require('packer-config')
require('nvim-tree-config')
require('lsp-config.language-servers')
require('lsp-config.nvim-cmp')
require('lualine-config')
require('barbar-config')
require('treesitter-config')
